cruiser = ["0", "6", "12"]
destroyer = ["14", "15"]
submarine = "21"
expected_hash = "0x04df209ed0aad0968c3aa95d735485f04ed83fb29173287fda6716461da5815d"
salt = "7"
pub_input = "75957860110562"
# (BigInt(18544399441)<<BigInt(12)) + (BigInt(14<<4)) + BigInt(2) = 75957860110562n
#hit_status = "2"
#shot_position = "14"
#grid_snapshot = "18544399441"
#grid_snapshot = [
#     "0", "1", "0", "0", "0", "1", 
#     "0", "1", "0", "0", "0", "1", 
#     "0", "1", "0", "1", "0", "1", 
#     "0", "1", "0", "0", "0", "1", 
#     "0", "1", "0", "0", "0", "1", 
#     "0", "1", "0", "0", "0", "1", 
#]