[profile.default]
src = "contract/src"
test = 'contract/test'
script = "contract/script"
out = "contract/out"
libs = ["lib"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 100000
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
