[profile.default]
src = "./src"
test = './test'
script = "./script"
out = "./out"
libs = ["../../lib"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 100
via_ir = false
bytecode_hash = "none"
cbor_metadata = false
